"""Gemeinsame deutsche Begriffe und Feldhilfen für Einrichtung und Oberfläche."""

PARAMETER_TEXT = {
    "session_light_minutes": ("Lichtnachlauf nach Sitzungsende", "Dauer ab dem endgültigen Sitzungsende, also nach der Pause bis zum Sitzungsende. Danach wird das Licht ausgeschaltet. Eine neue Sitzung beendet den Lichtnachlauf. Null schaltet das Licht direkt am Sitzungsende aus.", "operation"),
    "session_light_brightness_percent": ("Lichthelligkeit nach Sitzungsende", "Helligkeit während des Lichtnachlaufs nach einer beendeten Saunasitzung. Standard: 50 %. Der Nachlauf nach einem Saunagang und die Zwangskühlung haben eigene Lichtwerte.", "operation"),
    "temperature_increase_c": ("Temperaturerhöhung je Saunagang", "Erhöhung nach jedem weiteren gezählten Saunagang, höchstens bis zur Endtemperatur. Während der Sitzung änderbar; bereits gezählte Gänge werden nicht erneut angerechnet.", "temperature"),
    "final_temperature_c": ("Endtemperatur der Steigerung", "Obergrenze für die Solltemperatur. Leer lassen für eine konstante Temperatur. Eine niedrigere Endtemperatur begrenzt die aktuelle Solltemperatur; Heizsperren und laufende Fristen bleiben wirksam.", "temperature"),
    "target_temperature_c": ("Solltemperatur", "Gewünschte Temperatur am oberen Sensor während eines Saunagangs. Eine Änderung während der Sitzung gilt sofort; weitere Steigerungen beginnen ab diesem Wert.", "temperature"),
    "readiness_offset_c": ("Temperaturaufschlag für Bereitschaft", "Für die Bereitschaft wird die Solltemperatur um diesen Wert angehoben.", "temperature"),
    "readiness_hysteresis_c": ("Schaltabstand unter der Bereitschaftstemperatur", "Die Heizung darf wieder einschalten, wenn die Temperatur um diesen Wert unter die Bereitschaftstemperatur fällt.", "temperature"),
    "thermostat_cooldown_minutes": ("Heizpause nach Erreichen der Bereitschaft", "Wartezeit bis zum erneuten Heizen nach Erreichen der Bereitschaftstemperatur.", "temperature"),
    "minimum_heating_minutes": ("Mindestheizzeit nach dem Einschalten", "Verhindert kurze Heizintervalle. Nachlauf, Zwangskühlung, Ausschalten und Schutzabschaltung haben Vorrang.", "temperature"),
    "session_gap_minutes": ("Pause bis zum Sitzungsende", "Nach dieser Zeit mit ausgeschaltetem Saunabetrieb endet die Saunasitzung. Vorheriges Einschalten setzt sie fort.", "operation"),
    "confirmation_minutes": ("Zeit für die Aufgussbestätigung", "Zeit ab dem zugeordneten Gangbeginn. Ohne Aufguss wird der vorläufige Saunagang aufgehoben.", "operation"),
    "heating_minutes": ("Heizzeit bis zur ersten Zwangskühlung", "Gezählte Heizzeit, nach der die erste Zwangskühlung fällig wird.", "operation"),
    "heating_reduction_minutes": ("Verkürzung der Heizzeit nach erster Kühlung", "Wird nach der ersten abgeschlossenen Kühlung einmal von der Heizzeitgrenze abgezogen. Danach bleibt die Grenze gleich.", "operation"),
    "heat_reset_minutes": ("Ofen-Auszeit zum Zurücksetzen der Heizzeit", "Nach dieser zusammenhängenden Auszeit beginnt der Heizzeitzähler wieder bei null. Die Saunasitzung und ihr Energieverbrauch bleiben erhalten.", "operation"),
    "forced_cooling_minutes": ("Dauer der Zwangskühlung", "Zeit mit ausgeschaltetem Ofen. Ein vorausgehender Nachlauf wird vollständig angerechnet.", "operation"),
    "after_run_minutes": ("Nachlauf nach einem Saunagang", "Zeit nach einem beendeten, durch Aufguss bestätigten Saunagang. Der Ofen bleibt aus; neue Saunagänge sind gesperrt.", "operation"),
    "person_wait_minutes": ("Wartezeit nach dem Schließen der Tür", "Verschiebt eine fällige Zwangskühlung, damit eine eintretende Person erkannt werden kann.", "operation"),
    "open_door_wait_minutes": ("Wartezeit bei offen bleibender Tür", "Längster Kühlaufschub ab der Türöffnung während Aufheizen oder Bereitschaft.", "operation"),
    "cooling_brightness_percent": ("Lichthelligkeit bei Zwangskühlung", "Helligkeit des Saunalichts während einer laufenden Zwangskühlung.", "operation"),
    "operation_brightness_percent": ("Lichthelligkeit beim Einschalten", "Helligkeit des Saunalichts beim Einschalten des Saunabetriebs. Manuelle Lichtänderungen bleiben bis zum nächsten Einschalten erhalten.", "operation"),
    "after_run_brightness_percent": ("Lichthelligkeit im Nachlauf", "Helligkeit des Saunalichts während des Nachlaufs. Nach Nachlauf und anschließender Kühlung wird die vorherige Helligkeit wiederhergestellt.", "operation"),
    "safety_temperature_c": ("Temperaturgrenze für zusätzliche Kühlung", "Wird diese Temperatur anhaltend überschritten, ist eine verlängerte Zwangskühlung fällig; die Sitzung wird nicht abgebrochen.", "monitoring"),
    "overtemperature_minutes": ("Dauer der Temperaturüberschreitung", "Die Temperaturgrenze muss länger als diese Zeit ununterbrochen überschritten sein.", "monitoring"),
    "overtemperature_cooling_factor": ("Verlängerung der Kühlzeit bei Übertemperatur", "Faktor für die eingestellte Kühlzeit. Der Wert 2 bedeutet doppelte Kühlzeit.", "monitoring"),
    "sensor_timeout_seconds": ("Höchstalter eines Messwerts", "Nach dieser Zeit ohne neue Meldung gilt ein Sensorwert als veraltet. Der Standard beträgt 180 Sekunden. Bei Bedarf passend zum tatsächlichen Meldeabstand einstellen.", "monitoring"),
    "feedback_timeout_seconds": ("Wartezeit auf die Schützrückmeldung", "Zeit, in der der Schütz einen Ein- oder Ausschaltbefehl bestätigen muss.", "monitoring"),
    "fault_confirmation_seconds": ("Dauer bis zur bestätigten Störung", "Ein zentraler technischer Fehler muss so lange durchgehend bestehen, bevor die Schutzabschaltung den Ofen ausschaltet und verriegelt. Bei fehlender Regeltemperatur bleibt ein bereits laufender Heizvorgang während dieser Prüfung erhalten. Ein neuer Heizstart benötigt einen gültigen Temperaturwert; Nachlauf, Kühlung und Ausschalten bleiben vorrangig.", "monitoring"),
    "mechanical_timer_minutes": ("Laufzeit des mechanischen Ofentimers", "Geschätzte Laufzeit bei eingeschaltetem Saunabetrieb und eingeschaltetem Schütz. Bei ausgeschaltetem oder nicht verfügbarem Schütz hält die Anzeige an, auch während Heizpause, Nachlauf und Kühlung. Nach einer beendeten Sitzung mit gezählten Saunagängen beginnt sie beim nächsten Start neu. Die Anzeige schaltet nichts.", "timer"),
    "mechanical_timer_warning_minutes": ("Erinnerung vor Ablauf des Ofentimers", "So lange vor dem geschätzten Ablauf erscheint eine Erinnerung zum Einstellen des Drehschalters. Leer lassen, wenn keine Vorwarnung gewünscht ist.", "timer"),
    "nominal_power_kw": ("Ofenleistung für die Verbrauchsschätzung", "Nennleistung des Ofens in kW. Ohne Leistungsmessung wird daraus und aus der Heizzeit der Verbrauch in kWh berechnet.", "timer"),
    "power_heating_threshold_w": ("Leistungsschwelle für das Heizen", "Nur bei zugeordnetem Leistungssensor: Oberhalb dieser Leistung zählt die Zeit als Heizzeit. Standby bleibt beim Energieverbrauch berücksichtigt.", "timer"),
    "preset_start_c": ("Niedrigste Temperatur der Schnellauswahl", "Solltemperatur der ersten Taste in der Übersicht.", "display"),
    "preset_step_c": ("Temperaturabstand der Schnellauswahl", "Abstand zwischen zwei benachbarten Temperaturtasten.", "display"),
    "preset_count": ("Anzahl der Temperaturtasten", "Anzahl der sichtbaren Tasten für die Solltemperatur.", "display"),
    "grid_seconds": ("Zeitabstand der Auswertung", "Das feste Ein-Sekunden-Raster gehört zum geprüften Erkennungsverfahren.", "detection"),
    "median_seconds": ("Glättungszeit der Messwerte", "Zeitfenster für den Median. Es glättet einzelne Messausreißer vor der Erkennung.", "detection"),
    "door_window_seconds": ("Zeitfenster für den Temperaturtrend an der Tür", "Zeitraum für den Temperaturtrend zur Erkennung einer Türöffnung oder Türschließung.", "detection"),
    "door_humidity_seconds": ("Zeitfenster für die Luftfeuchteänderung an der Tür", "Zeitraum für den ergänzenden Luftfeuchteabfall bei einer Türöffnung.", "detection"),
    "door_open_slope": ("Temperaturtrend bei Türöffnung", "Die Temperatur muss mindestens so stark fallen. Negative Werte bezeichnen eine Abkühlung.", "detection"),
    "door_open_humidity_upper": ("Luftfeuchteabfall bei Türöffnung oben", "Mindestabfall am oberen Sensor in Prozentpunkten; wird zusammen mit dem Temperaturtrend bewertet.", "detection"),
    "door_open_humidity_lower": ("Luftfeuchteabfall bei Türöffnung unten", "Mindestabfall am unteren Sensor in Prozentpunkten; wird zusammen mit dem Temperaturtrend bewertet.", "detection"),
    "door_open_hold_seconds": ("Bestätigungsdauer der Türöffnung", "So lange müssen die Bedingungen für eine offene Tür bestehen.", "detection"),
    "door_heating_slope": ("Türöffnung: Temperaturabfall trotz eingeschalteter Heizung", "Zusätzliche Erkennung ohne Feuchteabfall: Beide Temperaturtrends müssen unter diesem Wert liegen, während die Heizung durchgehend eingeschaltet ist. Bei nur einer verfügbaren Messposition bleibt die bisherige Regel mit Luftfeuchte maßgeblich.", "detection"),
    "door_heating_hold_seconds": ("Bestätigungsdauer des Temperaturabfalls beim Heizen", "So lange muss der zusätzliche Temperaturabfall an beiden Messpositionen gleichzeitig bestehen. Eine Heizabschaltung verwirft diesen Nachweis.", "detection"),
    "door_heating_max_temperature_c": ("Temperaturgrenze der ergänzenden Türerkennung", "Nur solange beide geglätteten Temperaturen unter diesem Wert liegen, darf die zusätzliche Regel ohne Feuchteabfall auslösen. Im heißen Bereich bleibt die Regel mit Temperatur- und Feuchteabfall maßgeblich. Null schaltet die Ergänzung aus.", "detection"),
    "door_close_slope": ("Temperaturtrend bei Türschließung", "Mindestanstieg der Temperatur für die Erkennung einer geschlossenen Tür.", "detection"),
    "door_close_hold_seconds": ("Bestätigungsdauer der Türschließung", "So lange muss die Bedingung für eine geschlossene Tür bestehen.", "detection"),
    "vent_baseline_seconds": ("Vergleichszeit vor dem Lüften", "Rückblick für die Temperatur vor der Türöffnung.", "detection"),
    "vent_hold_seconds": ("Mindestdauer des Durchlüftens", "So lange muss die Tür offen sein, bevor Durchlüften bestätigt werden kann.", "detection"),
    "vent_drop_upper": ("Temperaturabfall beim Durchlüften oben", "Mindestabfall am oberen Sensor gegenüber der Temperatur vor der Öffnung.", "detection"),
    "vent_drop_lower": ("Temperaturabfall beim Durchlüften unten", "Mindestabfall am unteren Sensor gegenüber der Temperatur vor der Öffnung.", "detection"),
    "person_step_seconds": ("Zeitabstand der Personenprüfung", "Abstand zwischen zwei Auswertungen der Personenbedingungen.", "detection"),
    "strong_window_seconds": ("Zeitfenster für deutliche Personensignale", "Zeitraum für Temperatur- und Luftfeuchtetrends bei deutlichen Hinweisen auf Personen.", "detection"),
    "strong_humidity_upper": ("Luftfeuchtetrend bei deutlichem Personensignal oben", "Mindestanstieg am oberen Sensor in Prozentpunkten pro Minute.", "detection"),
    "strong_humidity_lower": ("Luftfeuchtetrend bei deutlichem Personensignal unten", "Mindestanstieg am unteren Sensor in Prozentpunkten pro Minute.", "detection"),
    "strong_temperature_upper": ("Temperaturtrend bei deutlichem Personensignal oben", "Untergrenze des Temperaturtrends am oberen Sensor für diesen Erkennungspfad.", "detection"),
    "strong_temperature_lower": ("Temperaturtrend bei deutlichem Personensignal unten", "Untergrenze des Temperaturtrends am unteren Sensor für diesen Erkennungspfad.", "detection"),
    "strong_hold_seconds": ("Bestätigungsdauer deutlicher Personensignale", "So lange müssen die Bedingungen für ein deutliches Personensignal bestehen.", "detection"),
    "weak_window_seconds": ("Zeitfenster für schwache Personensignale", "Längerer Vergleichszeitraum für schwache Personensignale nach bestätigtem Durchlüften.", "detection"),
    "weak_humidity_upper": ("Luftfeuchtetrend bei schwachem Personensignal oben", "Mindestanstieg am oberen Sensor in Prozentpunkten pro Minute.", "detection"),
    "weak_humidity_lower": ("Luftfeuchtetrend bei schwachem Personensignal unten", "Mindestanstieg am unteren Sensor in Prozentpunkten pro Minute.", "detection"),
    "weak_temperature_upper": ("Temperaturtrend bei schwachem Personensignal oben", "Untergrenze des Temperaturtrends am oberen Sensor nach dem Durchlüften.", "detection"),
    "weak_temperature_lower": ("Temperaturtrend bei schwachem Personensignal unten", "Untergrenze des Temperaturtrends am unteren Sensor nach dem Durchlüften.", "detection"),
    "weak_hold_seconds": ("Bestätigungsdauer schwacher Personensignale", "So lange müssen die Bedingungen für ein schwaches Personensignal bestehen.", "detection"),
    "infusion_window_seconds": ("Zeitfenster für die Aufgusserkennung", "Zeitraum, in dem Luftfeuchteanstieg und Temperaturänderung eines Aufgusses bewertet werden.", "detection"),
    "infusion_humidity": ("Luftfeuchteanstieg bei einem Aufguss", "Mindestanstieg in Prozentpunkten innerhalb des Aufgussfensters.", "detection"),
    "infusion_temperature": ("Temperaturänderung bei einem Aufguss", "Untergrenze der Temperaturänderung innerhalb des Aufgussfensters.", "detection"),
    "infusion_hold_seconds": ("Bestätigungsdauer des Aufgusssignals", "So lange müssen die Aufgussbedingungen bestehen. Dies ist nicht die Wartefrist eines vorläufigen Saunagangs.", "detection"),
}
